#!/bin/bash

source ./colors.sh;
source ./appConsoleFunctions.sh

printCommandsInfo()
{
    echo -e "
 ${CYAN}Server command line interface for the Docker-based web development environment demo.

${YELLOW} Usage:${ENDCOLOR}
    demo <command> [options] [arguments]

${YELLOW} Available commands: ${ENDCOLOR}${GREEN}
    status | ps ${BLUE}.....................................................................${GREEN} Print status of containers
    start | up ${BLUE}......................................................................${GREEN} Start the containers
    stop | down ${BLUE}.....................................................................${GREEN} Stop the containers
    restart ${BLUE}.........................................................................${GREEN} Restart the container
    pull ${BLUE}............................................................................${GREEN} Pull the containers
    build [--no-cache] ${BLUE}..............................................................${GREEN} Build containers
                                                                                            Options:
                                                                                                --no-cache ${BLUE}..........................${GREEN} Build no cache

    env ${BLUE}.............................................................................${GREEN} Copy project env
    docker-env [local, develop] ${BLUE}.....................................................${GREEN} Copy docker env

    install | i ${BLUE}.....................................................................${GREEN} Install project
    logs ${BLUE}............................................................................${GREEN} Print logs of containers
    bash ${BLUE}............................................................................${GREEN} Container interactive terminal bash
    cc ${BLUE}..............................................................................${GREEN} Clear cache

    artisan ${BLUE}.........................................................................${GREEN} Laravel Artisan commands
    composer ${BLUE}........................................................................${GREEN} Composer commands
    ${ENDCOLOR}
"
}

case "$1" in
    ps | status)
        status
    ;;
    up | start)
        start
    ;;
    down | stop)
        stop
    ;;
    restart)
        restart
    ;;
    pull)
        pull
    ;;
    build)
        build "${@:2}"
    ;;

    env)
        env
    ;;
    docker-env)
        dockerEnv "${@:2}"
    ;;

    install | i)
        install
    ;;
    logs)
        logs "${@:2}"
    ;;
    bash)
        bash
    ;;
    migrations)
        migrations "${@:2}"
    ;;
    cc)
        cc
    ;;
    database)
        database "${@:2}"
    ;;
    artisan)
        artisan "${@:2}"
    ;;
    composer)
        composer "${@:2}"
    ;;
    *)
        printCommandsInfo

        exit 1
    ;;
esac
